version: '3.8'

services:
  sqlserver-users:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver-users
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - users_data:/var/opt/mssql

  sqlserver-products:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver-products
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"
    volumes:
      - products_data:/var/opt/mssql

  user-service:
    build:
      context: .
      dockerfile: UserService/Dockerfile
    container_name: user-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=sqlserver-users;Database=UserDB;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;
      - OTEL_DOTNET_EXPERIMENTAL_METRICS_EXEMPLAR_FILTER=always_on
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://192.168.48.20:4317
    ports:
      - "5001:80"
    restart: on-failure

  product-service:
    build:
      context: .
      dockerfile: ProductService/Dockerfile
    container_name: product-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=sqlserver-products;Database=ProductDB;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;
      - OTEL_DOTNET_EXPERIMENTAL_METRICS_EXEMPLAR_FILTER=always_on
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://192.168.48.20:4317
    ports:
      - "5002:80"
    restart: on-failure

volumes:
  users_data:
  products_data:
